package com.mycompany.itpm;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author abinath
 */
public class Addkocation extends javax.swing.JFrame {

     Connection connect=null;
    /**
     * Creates new form Addkocation
     */
    public Addkocation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lecturehall = new javax.swing.JRadioButton();
        Laboratory = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Roomname = new javax.swing.JTextField();
        Buildingname = new javax.swing.JTextField();
        Capacity = new javax.swing.JTextField();
        cap = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Building Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 210, 110, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Room Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 270, 130, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Room Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 140, 120, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Capacity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 330, 110, 15);

        buttonGroup1.add(Lecturehall);
        Lecturehall.setText("Lecture hall");
        Lecturehall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturehallActionPerformed(evt);
            }
        });
        getContentPane().add(Lecturehall);
        Lecturehall.setBounds(420, 260, 100, 30);

        buttonGroup1.add(Laboratory);
        Laboratory.setText("Laboratory");
        Laboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaboratoryActionPerformed(evt);
            }
        });
        getContentPane().add(Laboratory);
        Laboratory.setBounds(530, 260, 110, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 380, 70, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 380, 60, 30);

        Roomname.setText(" ");
        Roomname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomnameActionPerformed(evt);
            }
        });
        getContentPane().add(Roomname);
        Roomname.setBounds(420, 130, 140, 30);

        Buildingname.setText(" ");
        Buildingname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingnameActionPerformed(evt);
            }
        });
        getContentPane().add(Buildingname);
        Buildingname.setBounds(420, 200, 140, 30);

        Capacity.setText(" ");
        Capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacityActionPerformed(evt);
            }
        });
        getContentPane().add(Capacity);
        Capacity.setBounds(420, 320, 140, 30);
        getContentPane().add(cap);
        cap.setBounds(400, 360, 272, 12);

        jButton3.setText("Manage Location");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(273, 60, 150, 31);

        jButton4.setText("Add Location");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(146, 60, 120, 31);

        jButton5.setText("Manage Session");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(430, 60, 140, 31);

        jButton6.setText("Add Session");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(581, 60, 110, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("ABC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 100);

        btn_back.setBackground(new java.awt.Color(255, 102, 255));
        btn_back.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_back.setText("Back to main manu ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(50, 380, 163, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LecturehallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturehallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LecturehallActionPerformed

    private void LaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaboratoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaboratoryActionPerformed

    private void BuildingnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildingnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try 
                {
                Class.forName("com.mysql.jdbc.Driver");
                connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
                System.out.println("database is connected");
                Lecturehall.setActionCommand("Lecturehall");
                Laboratory.setActionCommand("Laboratory");
                PreparedStatement sql=connect.prepareStatement("INSERT INTO `locationdetails`( `buildingname`, `roomname`, `roomtype`, `capacity`) VALUES (?,?,?,?)");
                sql.setString(1,Buildingname.getText());
                 sql.setString(2,Roomname.getText());
                  sql.setString(3,buttonGroup1.getSelection().getActionCommand());
                  //validation
                 int capacity=Integer.parseInt(Capacity.getText());
                  
                  
                  
                   sql.setInt(4,capacity);
                   int Success=sql.executeUpdate();
                   if(Success>0)
                   {
                      
                        JOptionPane.showMessageDialog(null, "Location added");
                       Buildingname.setText("");
        Roomname.setText("");
        Capacity.setText("");
        Lecturehall.setSelected(false);
        Laboratory.setSelected(false);
         cap.setText("");
                   }
                  
                }catch(NumberFormatException e){
                   cap.setText("* capacity must be integer");
                   Capacity.setText("");
                   Capacity.requestFocusInWindow();
              }  
        catch(Exception a){
          
               System.out.println("error");
              }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Buildingname.setText("");
        Roomname.setText("");
        Capacity.setText("");
        Lecturehall.setSelected(false);
        Laboratory.setSelected(false);
         cap.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Managelocation1().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         dispose();
        new addlocation_session().setVisible(true);
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacityActionPerformed

    private void RoomnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        new manage_session().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:

        mainMenu mm = new mainMenu();

        mm.show(); // Display mainMenu here

        dispose(); // close current frame homepage
    }//GEN-LAST:event_btn_backActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addkocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addkocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addkocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addkocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//            new Managelocation1().setVisible(true);
              new Addkocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buildingname;
    private javax.swing.JTextField Capacity;
    private javax.swing.JRadioButton Laboratory;
    private javax.swing.JRadioButton Lecturehall;
    private javax.swing.JTextField Roomname;
    private javax.swing.JButton btn_back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
