package com.mycompany.itpm;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;
/**
 *
 * @author abinath
 */
public class Managelocation1 extends javax.swing.JFrame {
    Connection connect=null;

    /**
     * Creates new form Managelocation1
     */
    public Managelocation1() {
        initComponents();
         getDetails();
    }
            private void getDetails(){
                
                try 
                {
                Class.forName("com.mysql.jdbc.Driver");
                connect=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
                System.out.println("database is connected");
                Lecturerhall.setActionCommand("Lecturehall");
                   Laboratory.setActionCommand("Laboratory");
                   DefaultTableModel m=(DefaultTableModel)Managetable.getModel();
            PreparedStatement sql=connect.prepareStatement("SELECT `ID`, `buildingname`, `roomname`, `roomtype`, `capacity` FROM `locationdetails`");
        
                ResultSet Q=sql.executeQuery();
                 while(Q.next())
                 {
                    
                  System.out.println(Q.getString(1));                
       
                  String id=Q.getString(1);
                   String Buildingname=Q.getString(2);
                    String Roomname=Q.getString(3);
                     String Roomtype=Q.getString(4);
                      String Capacity=Q.getString(5);
                     
                      m.addRow(new Object[]{id,Buildingname,Roomname,Roomtype,Capacity});
                      
                 } 
                 Managetable.setModel(m);
                   System.out.println("running");
                }
        catch(Exception a){
                System.out.println("Error");
              }
                
                
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Laboratory = new javax.swing.JRadioButton();
        ubdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Buildingname = new javax.swing.JTextField();
        Roomname = new javax.swing.JTextField();
        Capasity = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Managetable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lecturerhall = new javax.swing.JRadioButton();
        cap = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        buttonGroup1.add(Laboratory);
        Laboratory.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Laboratory.setText("Laboratory");
        getContentPane().add(Laboratory);
        Laboratory.setBounds(480, 360, 100, 23);

        ubdate.setBackground(new java.awt.Color(51, 51, 255));
        ubdate.setText("Update");
        ubdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubdateActionPerformed(evt);
            }
        });
        getContentPane().add(ubdate);
        ubdate.setBounds(664, 145, 70, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 330, 80, 30);

        Buildingname.setText(" ");
        Buildingname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingnameActionPerformed(evt);
            }
        });
        getContentPane().add(Buildingname);
        Buildingname.setBounds(340, 270, 110, 30);

        Roomname.setText(" ");
        getContentPane().add(Roomname);
        Roomname.setBounds(340, 320, 110, 30);

        Capasity.setText(" ");
        getContentPane().add(Capasity);
        Capasity.setBounds(340, 410, 120, 30);

        delete.setBackground(new java.awt.Color(255, 0, 51));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(664, 196, 70, 30);

        Managetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Building Name", "Room name", "Room type", "Capacity"
            }
        ));
        Managetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManagetableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Managetable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(151, 104, 495, 138);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Bulding name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(179, 275, 90, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Room name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(179, 325, 70, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Room type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(179, 366, 70, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Capacity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(179, 415, 70, 14);

        buttonGroup1.add(Lecturerhall);
        Lecturerhall.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Lecturerhall.setText("Lecturer hall");
        Lecturerhall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturerhallActionPerformed(evt);
            }
        });
        getContentPane().add(Lecturerhall);
        Lecturerhall.setBounds(340, 360, 93, 23);
        getContentPane().add(cap);
        cap.setBounds(337, 438, 241, 16);

        jButton1.setText("Add Location");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 40, 150, 31);

        jButton3.setText("Manage Location");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 40, 150, 31);

        jButton4.setText("Manage Session");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(470, 40, 150, 31);

        jButton5.setText("Add Session");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(630, 40, 120, 31);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -3, 790, 460);

        btn_back.setBackground(new java.awt.Color(255, 102, 255));
        btn_back.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_back.setText("Back to main manu ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(0, 0, 230, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ubdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubdateActionPerformed
        // TODO add your handling code here:
         Connection connect=null;
          DefaultTableModel m=(DefaultTableModel)Managetable.getModel();
         int click=Managetable.getSelectedRow();
         String clickid=m.getValueAt(click,0).toString();
        try 
                {
                Class.forName("com.mysql.jdbc.Driver");
                connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
                System.out.println("database is connected");
                Lecturerhall.setActionCommand("Lecturehall");
                   Laboratory.setActionCommand("Laboratory");
                PreparedStatement sql=connect.prepareStatement("UPDATE `locationdetails` SET `buildingname`=?,`roomname`=?,`roomtype`=?,`capacity`=? WHERE ID=?");
                sql.setString(5,clickid);
                sql.setString(1,Buildingname.getText());
                sql.setString(2,Roomname.getText());
                sql.setString(3,buttonGroup1.getSelection().getActionCommand());
                
                int capacity=Integer.parseInt(Capasity.getText());
                 sql.setInt(4,capacity); 
                  
                  
                   
                  

                   int Success=sql.executeUpdate();
                   if(Success>0)
                   {
                       System.out.println("Again Location added");
                       dispose();
                      JOptionPane.showMessageDialog(null, "updated");

                       new Managelocation1().setVisible(true);
                       
                   }
                  
               
                }catch(NumberFormatException e){
                   cap.setText("* capacity must be integer");
                   Capasity.setText("");
                   Capasity.requestFocusInWindow();
              }  
        catch(Exception a){
                System.out.println("Error");
              }
        
    }//GEN-LAST:event_ubdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Buildingname.setText("");
        Roomname.setText("");
        Capasity.setText("");
        Lecturerhall.setSelected(false);
        Laboratory.setSelected(false);
       cap.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BuildingnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildingnameActionPerformed

    private void LecturerhallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturerhallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LecturerhallActionPerformed

    private void ManagetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagetableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel m=(DefaultTableModel)Managetable.getModel();
         int click=Managetable.getSelectedRow();
         String clickid=m.getValueAt(click,0).toString();
         try 
                {
                Class.forName("com.mysql.jdbc.Driver");
                connect=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
                System.out.println("database is connected");
                Lecturerhall.setActionCommand("Lecturehall");
                   Laboratory.setActionCommand("Laboratory");
               // Lecture Hall
               //Laboratory
            PreparedStatement sql=connect.prepareStatement("SELECT `buildingname`, `roomname`, `roomtype`, `capacity` FROM `locationdetails` Where ID=?");
            sql.setString(1, clickid);
                ResultSet Q=sql.executeQuery();
                 while(Q.next())
                 {
                 Buildingname.setText(Q.getString(1));
                    Roomname.setText(Q.getString(2));
                       String gg=Q.getString(3);
                       switch(gg){
                           case "Lecture Hall":
                               Lecturerhall.setSelected(true);
                               break;
                           case "Laboratory":
                               Laboratory.setSelected(true);
                               break;
                       }
                          Capasity.setText(Q.getString(4));
                 } 
                  
                }
        catch(Exception a){
                System.out.println("Error");
              }
         
    }//GEN-LAST:event_ManagetableMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

    
           Connection connect=null;
          DefaultTableModel m=(DefaultTableModel)Managetable.getModel();
         int click=Managetable.getSelectedRow();
         String clickid=m.getValueAt(click,0).toString();
        int a ;
 try 
                {
                Class.forName("com.mysql.jdbc.Driver");
                connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
                System.out.println("database is connected");
                PreparedStatement sql=connect.prepareStatement("DELETE FROM `locationdetails`  WHERE ID=?");
                sql.setString(1,clickid);
  
                   int Success=sql.executeUpdate();
                   if(Success>0)
                   {
                       System.out.println("deleted");
                       dispose();
                      JOptionPane.showMessageDialog(null, "deleted");

                       new Managelocation1().setVisible(true);
                   }
                  
               
                }
        catch(Exception f){
                System.out.println("Error");
              }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Addkocation().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         dispose();
        new manage_session().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         dispose();
        new addlocation_session().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:

        mainMenu mm = new mainMenu();

        mm.show(); // Display mainMenu here

        dispose(); // close current frame homepage
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Managelocation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Managelocation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Managelocation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Managelocation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new Managelocation1().setVisible(true);

//            new Addkocation().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buildingname;
    private javax.swing.JTextField Capasity;
    private javax.swing.JRadioButton Laboratory;
    private javax.swing.JRadioButton Lecturerhall;
    private javax.swing.JTable Managetable;
    private javax.swing.JTextField Roomname;
    private javax.swing.JButton btn_back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cap;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ubdate;
    // End of variables declaration//GEN-END:variables
}
