/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.itpm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class manage_student extends javax.swing.JFrame {

  

 

    /**
     * Creates new form manage_student
     */
    public manage_student() {
        initComponents();
        Connect();
        Load();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_student.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(add_student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
  
    public void Load(){
        int c;
        try {
            pst=con.prepareStatement("select* from student_group");
            rs=pst.executeQuery();
            
            ResultSetMetaData rsd=rs.getMetaData();
            c=rsd.getColumnCount();
            
            DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next()){
                Vector v2= new Vector();
                for(int i=1;i<=c;i++){
                   
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("semi"));
                    v2.add(rs.getString("prog"));
                    v2.add(rs.getString("gno"));
                    v2.add(rs.getString("sno"));
                    v2.add(rs.getString("groupid"));
                    v2.add(rs.getString("subgroupid"));
                    
                }
                d.addRow(v2);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(add_student.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    
     public static void AddRowToJTable(Object[] dataRow){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(dataRow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        txt_sid = new javax.swing.JTextField();
        cmb_pro = new javax.swing.JComboBox<>();
        cmb_gno = new javax.swing.JComboBox<>();
        cmb_sno = new javax.swing.JComboBox<>();
        txt_gid = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_dl = new javax.swing.JButton();
        btn_up = new javax.swing.JButton();
        btn_cl = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_addSg = new javax.swing.JButton();
        btn_genid = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Year & Sem ", "Programme", "Group No", "Sub Group No ", "Group ID", "Sub Group ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("ABC");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Year & Semester");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Programme");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Group No");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Sub Group NO");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Group ID");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Sub Group ID");

        txt_year.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_sid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cmb_pro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb_pro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "SE", "CSNE", "CS", "ISE", "CIVIL ENG", "MECHANICAL", "EEE", "BUSINESS", "LAW" }));

        cmb_gno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb_gno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cmb_sno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb_sno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        txt_gid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btn_save.setBackground(new java.awt.Color(255, 255, 102));
        btn_save.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_dl.setBackground(new java.awt.Color(255, 255, 102));
        btn_dl.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_dl.setText("Delete");
        btn_dl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dlActionPerformed(evt);
            }
        });

        btn_up.setBackground(new java.awt.Color(255, 255, 102));
        btn_up.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_up.setText("Update");
        btn_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upActionPerformed(evt);
            }
        });

        btn_cl.setBackground(new java.awt.Color(255, 255, 102));
        btn_cl.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_cl.setText("Clear");
        btn_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setText("Insitution");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Manage Student Group");

        btn_addSg.setBackground(new java.awt.Color(255, 153, 153));
        btn_addSg.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_addSg.setText("Add Student Group");
        btn_addSg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSgActionPerformed(evt);
            }
        });

        btn_genid.setBackground(new java.awt.Color(51, 204, 0));
        btn_genid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_genid.setText("Generate IDs");
        btn_genid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genidActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(255, 102, 255));
        btn_back.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_back.setText("Back to main manu ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_year)
                            .addComponent(txt_sid)
                            .addComponent(cmb_pro, 0, 149, Short.MAX_VALUE)
                            .addComponent(cmb_gno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_sno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_gid))
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(btn_addSg, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(btn_genid, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btn_back)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addSg))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_up)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_gno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_gid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_genid))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_sno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btn_dl)))
                        .addGap(50, 50, 50)
                        .addComponent(btn_cl)
                        .addGap(18, 18, 18)
                        .addComponent(btn_back)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String semi= txt_year.getText();
        String prog = cmb_pro.getSelectedItem().toString();
        String gno = cmb_gno.getSelectedItem().toString();
        String sno = cmb_sno.getSelectedItem().toString();
        String groupid= txt_gid.getText();
        String subgroupid= txt_sid.getText();
        try {
            pst=con.prepareStatement("insert into student_group (semi,prog,gno,sno,groupid,subgroupid) values(?,?,?,?,?,?)");
           
            pst.setString(1,semi );
            pst.setString(2, prog);
            pst.setString(3, gno);
            pst.setString(4, sno);
            pst.setString(5, groupid);
            pst.setString(6, subgroupid);
           int k = pst.executeUpdate();
           
           if(k==1){
               JOptionPane.showMessageDialog(this," Added");
             
                txt_year.setText("");
                cmb_pro.setSelectedItem("");
                cmb_gno.setSelectedItem("");
                cmb_sno.setSelectedItem("");
                txt_gid.setText("");
                txt_sid.setText("");
                txt_year.requestFocus();
              
                Load();
               
               
           }
           else{
               JOptionPane.showMessageDialog(this,"Error");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(add_student.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_genidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genidActionPerformed
        String semi = txt_year.getText();
        String prog = cmb_pro.getSelectedItem().toString();

        String gno = cmb_gno.getSelectedItem().toString();
        

        String sno = cmb_sno.getSelectedItem().toString();
        
        //for sid
        String sid = semi + "." + prog + "." + gno + "." + sno;
        txt_sid.setText(sid);
        
      
        //for groupid
        String gid = semi + "." + prog + "." + gno;
        txt_gid.setText(gid);
    }//GEN-LAST:event_btn_genidActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        txt_year.setText(d1.getValueAt(selectIndex, 1).toString());
        cmb_pro.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
        cmb_gno.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());
        cmb_sno.setSelectedItem(d1.getValueAt(selectIndex, 4).toString());
        txt_gid.setText(d1.getValueAt(selectIndex, 5).toString());
        txt_sid.setText(d1.getValueAt(selectIndex, 6).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upActionPerformed
       DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        
        String semi= txt_year.getText();
        String prog = cmb_pro.getSelectedItem().toString();
        String gno = cmb_gno.getSelectedItem().toString();
        String sno = cmb_sno.getSelectedItem().toString();
        String groupid= txt_gid.getText();
        String subgroupid= txt_sid.getText();
        try {
            pst=con.prepareStatement("update student_group set semi=?,prog=?,gno=?,sno=?,groupid=?,subgroupid=? where id=?");
           
            pst.setString(1,semi );
            pst.setString(2, prog);
            pst.setString(3, gno);
            pst.setString(4, sno);
            pst.setString(5, groupid);
            pst.setString(6, subgroupid);
            pst.setInt(7, id);
           int k = pst.executeUpdate();
           
           if(k==1){
               JOptionPane.showMessageDialog(this," updated");
             
                txt_year.setText("");
                cmb_pro.setSelectedItem("");
                cmb_gno.setSelectedItem("");
                cmb_sno.setSelectedItem("");
                txt_gid.setText("");
                txt_sid.setText("");
                txt_year.requestFocus();
              
                Load();
               
               
           }
           else{
               JOptionPane.showMessageDialog(this,"Error");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(add_student.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
    }//GEN-LAST:event_btn_upActionPerformed

    private void btn_dlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dlActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        
        try{
            
            pst=con.prepareStatement("delete from student_group where id=?");
            pst.setInt(1,id);
            
            int k= pst.executeUpdate();
            
            if(k==1){
                JOptionPane.showMessageDialog(this,"Deleted");
                
                txt_year.setText("");
                cmb_pro.setSelectedItem("");
                cmb_gno.setSelectedItem("");
                cmb_sno.setSelectedItem("");
                txt_gid.setText("");
                txt_sid.setText("");
                txt_year.requestFocus();
                btn_save.setEnabled(true);
                Load();
            
            }
            else{
            
                JOptionPane.showMessageDialog(this,"Error");
            }
        }catch(SQLException ex){
            Logger.getLogger(add_student.class.getName()).log(Level.SEVERE,null,ex);
        
        }
        
    }//GEN-LAST:event_btn_dlActionPerformed

    private void btn_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clActionPerformed
                txt_year.setText("");
                cmb_pro.setSelectedIndex(0);
                cmb_gno.setSelectedIndex(0);
                cmb_sno.setSelectedIndex(0);
                txt_gid.setText("");
                txt_sid.setText("");
    }//GEN-LAST:event_btn_clActionPerformed

    private void btn_addSgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSgActionPerformed
       add_student addS = new add_student();
       addS.show();
       dispose();
    }//GEN-LAST:event_btn_addSgActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
         mainMenu mm = new mainMenu();
          mm.show();
          dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addSg;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cl;
    private javax.swing.JButton btn_dl;
    private javax.swing.JButton btn_genid;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_up;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_gno;
    private javax.swing.JComboBox<String> cmb_pro;
    private javax.swing.JComboBox<String> cmb_sno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_gid;
    private javax.swing.JTextField txt_sid;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
