/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.itpm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WindowsUser
 */
public class NonOversession1 extends javax.swing.JFrame {

    /**
     * Creates new form Consession
     */
    public NonOversession1() {
        initComponents();
        Connect();
        con_load();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NonOversession1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NonOversession1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    void  con_load(){
        int c;
        try {
            pst=con.prepareStatement("select* from sessiondetails");
            rs=pst.executeQuery();
            
            ResultSetMetaData rsd=rs.getMetaData();
            c=rsd.getColumnCount();
            
            DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next()){
                Vector v2= new Vector();
                for(int i=1;i<=c;i++){
                   
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("lecturer1"));
                    v2.add(rs.getString("lecturer2"));
                    v2.add(rs.getString("subject"));
                    v2.add(rs.getString("group"));
                    v2.add(rs.getString("tag"));
                    v2.add(rs.getString("noofstudents"));
                    v2.add(rs.getString("duration"));
                    v2.add(rs.getString("room"));
                    
                    
                }
                d.addRow(v2);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(NonOversession1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add_ses = new javax.swing.JButton();
        add_mses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_par = new javax.swing.JButton();
        btn_par1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_lec = new javax.swing.JButton();
        btn_stu = new javax.swing.JButton();
        btn_lec2 = new javax.swing.JButton();
        btn_lec3 = new javax.swing.JButton();
        btn_lec4 = new javax.swing.JButton();
        btn_lec5 = new javax.swing.JButton();
        btn_lec6 = new javax.swing.JButton();
        btn_lec7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_btnAddSes = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("ABC");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Insitution");

        add_ses.setBackground(new java.awt.Color(255, 255, 153));
        add_ses.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add_ses.setText("Add Session");

        add_mses.setBackground(new java.awt.Color(255, 255, 153));
        add_mses.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add_mses.setText("Manage session");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Session");

        btn_par.setBackground(new java.awt.Color(255, 255, 102));
        btn_par.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_par.setText("Parallel");

        btn_par1.setBackground(new java.awt.Color(255, 255, 102));
        btn_par1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_par1.setText("Non Overlapping");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Consecutive");

        btn_lec.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_lec.setText("Lecturer");
        btn_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lecActionPerformed(evt);
            }
        });

        btn_stu.setBackground(new java.awt.Color(255, 255, 153));
        btn_stu.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_stu.setText("Student");
        btn_stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stuActionPerformed(evt);
            }
        });

        btn_lec2.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_lec2.setText("Subject");
        btn_lec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lec2ActionPerformed(evt);
            }
        });

        btn_lec3.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_lec3.setText("Location");

        btn_lec4.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_lec4.setText("Tag");
        btn_lec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lec4ActionPerformed(evt);
            }
        });

        btn_lec5.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_lec5.setText("Session");
        btn_lec5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lec5ActionPerformed(evt);
            }
        });

        btn_lec6.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_lec6.setText("Day & Time");
        btn_lec6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lec6ActionPerformed(evt);
            }
        });

        btn_lec7.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_lec7.setText("Graph");
        btn_lec7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lec7ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lecture 1", "Lecture 2", "Subject", "Group", "Tag", "NO Of Students", "Duration", "Room"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_btnAddSes.setBackground(new java.awt.Color(255, 255, 102));
        btn_btnAddSes.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_btnAddSes.setText("Add Session");
        btn_btnAddSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_btnAddSesActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(255, 102, 255));
        btn_back.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_back.setText("Back to main manu ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_lec7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_lec4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_lec2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_lec3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_stu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_lec5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_lec6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(239, 239, 239)
                                .addComponent(btn_btnAddSes, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(add_ses, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_mses))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(176, 176, 176))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addComponent(btn_par, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btn_par1)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_ses)
                            .addComponent(add_mses)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_par)
                                    .addComponent(btn_par1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btn_lec)
                                .addGap(18, 18, 18)
                                .addComponent(btn_stu)
                                .addGap(29, 29, 29)
                                .addComponent(btn_lec2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_lec3)
                                .addGap(22, 22, 22)
                                .addComponent(btn_lec4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addComponent(btn_lec5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lec6)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_btnAddSes)
                        .addGap(40, 40, 40)))
                .addComponent(btn_lec7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lec6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lec6ActionPerformed
        // TODO add your handling code here:
        addWorking ad = new addWorking();
        ad.show();;
        dispose();
    }//GEN-LAST:event_btn_lec6ActionPerformed

    private void btn_btnAddSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_btnAddSesActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
        if(d1.getRowCount()==0){
        //if table empty
            JOptionPane.showMessageDialog(this,"This table empty");
        }
        else
        {
            //not empty
            //db connection
            
                String Sid ,Lec1 ,Lec2 ,Sub ,Group ,Tag,NoS ,Du ,Room ;
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage?useSSL=false","root","");
                        for(int i=0;i<d1.getRowCount();i++){
                             Sid=d1.getValueAt(i,0).toString();
                             Lec1=d1.getValueAt(i,1).toString();
                             Lec2=d1.getValueAt(i,2).toString();
                             Sub=d1.getValueAt(i,3).toString();
                             Group=d1.getValueAt(i,4).toString();
                             Tag=d1.getValueAt(i,5).toString();
                             NoS=d1.getValueAt(i,6).toString();
                             Du=d1.getValueAt(i,7).toString();
                             Room=d1.getValueAt(i,8).toString();
                        
                     
                        
                        String query =" insert into NonOversession(ses_id,lecture1,lecture2,subject,groupid,tag,noofstudent,duration,room)values(?,?,?,?,?,?,?,?,?)";
                        pst= con.prepareStatement(query);
                        pst.setString(1, Sid);
                        pst.setString(2, Lec1);
                         pst.setString(3, Lec2);
                        pst.setString(4, Sub);
                        pst.setString(5, Group);
                        pst.setString(6, Tag);
                        pst.setString(7, NoS);
                         pst.setString(8, Du);
                          pst.setString(9, Room);
                          
                          
                        pst.execute();
                        
                    }
                     JOptionPane.showMessageDialog(this,"Consecutive sessions inserted");
                     d1.setRowCount(0);
                    
                }  catch (Exception e) {
                   
                }
                }
    }//GEN-LAST:event_btn_btnAddSesActionPerformed

    private void btn_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lecActionPerformed
        // TODO add your handling code here:
        Addlecturer al =new Addlecturer();
        al.show();
        dispose();
    }//GEN-LAST:event_btn_lecActionPerformed

    private void btn_stuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stuActionPerformed
        // TODO add your handling code here:
        add_student  as =new add_student();
        as.show();
        dispose();
    }//GEN-LAST:event_btn_stuActionPerformed

    private void btn_lec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lec2ActionPerformed
        // TODO add your handling code here:
        Addsubject adl = new  Addsubject();
        adl.show();
        dispose();
    }//GEN-LAST:event_btn_lec2ActionPerformed

    private void btn_lec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lec4ActionPerformed
        // TODO add your handling code here:
        addtag  as =new addtag();
        as.show();
        dispose();
    }//GEN-LAST:event_btn_lec4ActionPerformed

    private void btn_lec5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lec5ActionPerformed
        // TODO add your handling code here:
        AddSession  as =new AddSession();
        as.show();
        dispose();
    }//GEN-LAST:event_btn_lec5ActionPerformed

    private void btn_lec7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lec7ActionPerformed
        // TODO add your handling code here:
         statistics1 s =new statistics1();
        s.show();
        dispose();
    }//GEN-LAST:event_btn_lec7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonOversession1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonOversession1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonOversession1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonOversession1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NonOversession1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_mses;
    private javax.swing.JButton add_ses;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_btnAddSes;
    private javax.swing.JButton btn_lec;
    private javax.swing.JButton btn_lec2;
    private javax.swing.JButton btn_lec3;
    private javax.swing.JButton btn_lec4;
    private javax.swing.JButton btn_lec5;
    private javax.swing.JButton btn_lec6;
    private javax.swing.JButton btn_lec7;
    private javax.swing.JButton btn_par;
    private javax.swing.JButton btn_par1;
    private javax.swing.JButton btn_stu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
