/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.itpm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author WindowsUser
 */
public class Session_NotAvai_le extends javax.swing.JFrame {

    /**
     * Creates new form Session_NotAvailableTime
     */
    public Session_NotAvai_le() {
        initComponents();
        Connect();
        combol();
        sesCombL();
        grupCombL();
        subCombL();
    }

    Connection con;
    PreparedStatement pst;
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    void combol(){
    try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
            pst = con.prepareStatement("Select distinct L_Name from lecturer");
            ResultSet rs= pst.executeQuery();
            
            while(rs.next()){
              cmb_lec.addItem(rs.getString("l_name"));
              cmb_lec.setSelectedItem("");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    void sesCombL(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
            pst = con.prepareStatement("Select distinct id from sessiondetails");
            ResultSet rs= pst.executeQuery();
            
            while(rs.next()){
              cmb_session.addItem(rs.getString("id"));
              cmb_session.setSelectedItem("");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    void grupCombL(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
            pst = con.prepareStatement("Select distinct groupid from student_group");
            ResultSet rs= pst.executeQuery();
            
            while(rs.next()){
              cmb_gid.addItem(rs.getString("groupid"));
              cmb_gid.setSelectedItem("");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    void subCombL(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
            pst = con.prepareStatement("Select distinct subgroupid from student_group");
            ResultSet rs= pst.executeQuery();
            
            while(rs.next()){
              cmb_sid.addItem(rs.getString("subgroupid"));
              cmb_sid.setSelectedItem("");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ABC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Lecture = new javax.swing.JButton();
        Btn_Student = new javax.swing.JButton();
        Btn_Subject = new javax.swing.JButton();
        Btn_Location = new javax.swing.JButton();
        Btn_Tag = new javax.swing.JButton();
        Btn_Session = new javax.swing.JButton();
        Btn_Day = new javax.swing.JButton();
        Btn_Graph = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_addLec = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_mnLec = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmb_lec = new javax.swing.JComboBox<>();
        cmb_gid = new javax.swing.JComboBox<>();
        cmb_sid = new javax.swing.JComboBox<>();
        cmb_session = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmb_time = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        ABC.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ABC.setText("ABC");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Insitution");

        Btn_Lecture.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Lecture.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Lecture.setText("Lecturer");
        Btn_Lecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LectureActionPerformed(evt);
            }
        });

        Btn_Student.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Student.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Student.setText("Student");
        Btn_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StudentActionPerformed(evt);
            }
        });

        Btn_Subject.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Subject.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Subject.setText("Subject");
        Btn_Subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubjectActionPerformed(evt);
            }
        });

        Btn_Location.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Location.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Location.setText("Location");
        Btn_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LocationActionPerformed(evt);
            }
        });

        Btn_Tag.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Tag.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Tag.setText("Tag");
        Btn_Tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TagActionPerformed(evt);
            }
        });

        Btn_Session.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Session.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Session.setText("Session");
        Btn_Session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SessionActionPerformed(evt);
            }
        });

        Btn_Day.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Day.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Day.setText("Day & Time");
        Btn_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DayActionPerformed(evt);
            }
        });

        Btn_Graph.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Graph.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Graph.setText("Graph");
        Btn_Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GraphActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Not available time");

        btn_addLec.setBackground(new java.awt.Color(204, 204, 204));
        btn_addLec.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_addLec.setText("Add Lecturer");
        btn_addLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addLecActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Add Session");

        btn_mnLec.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_mnLec.setText("Manage Lecturer");
        btn_mnLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mnLecActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Lecture Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Time");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Group ID");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Sub Group ID");

        cmb_lec.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_lecActionPerformed(evt);
            }
        });

        cmb_gid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        cmb_sid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        cmb_session.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btn_save.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cmb_time.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8.30", "9.30", "10.30", "11.30", "12.30", "1.30", "2.30", "3.30", "4.30" }));
        cmb_time.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Session ID");

        btn_back.setBackground(new java.awt.Color(255, 102, 255));
        btn_back.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_back.setText("Back to main manu ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_Subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_Location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_Tag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_Session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_Day, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                .addComponent(Btn_Lecture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(119, 119, 119)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmb_lec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmb_gid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmb_sid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmb_session, 0, 201, Short.MAX_VALUE)
                                                .addComponent(cmb_time, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(67, 67, 67)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(436, 436, 436))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(294, 294, 294)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ABC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_addLec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btn_mnLec, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(btn_back)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ABC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_addLec)
                        .addComponent(btn_mnLec))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Btn_Lecture)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_lec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Subject)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_gid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(9, 9, 9)
                .addComponent(Btn_Student)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(Btn_Location)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Tag))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cmb_session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(cmb_sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Session)
                            .addComponent(cmb_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Day))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_save)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(Btn_Graph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void Btn_LectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LectureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_LectureActionPerformed

    private void btn_addLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addLecActionPerformed
        // TODO add your handling code here:
        Addlecturer al =new Addlecturer();
        al.show();
        dispose();
    }//GEN-LAST:event_btn_addLecActionPerformed

    private void btn_mnLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mnLecActionPerformed
        // TODO add your handling code here:
        Managelecturer mn =  new Managelecturer();
        mn.show();
        dispose();
    }//GEN-LAST:event_btn_mnLecActionPerformed

    private void cmb_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_lecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_lecActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String LectureName= cmb_lec.getSelectedItem().toString();
        String GroupID= cmb_gid.getSelectedItem().toString();
        String SubGroupID= cmb_sid.getSelectedItem().toString();
        String SessionID= cmb_session.getSelectedItem().toString();
        String Time= cmb_time.getSelectedItem().toString();
        
        
        try {
            pst=con.prepareStatement("insert into notavailablelecture(lectureName,groupId,subgroupId,sessionId,time)values(?,?,?,?,?)");
           
            pst.setString(1, LectureName);
            pst.setString(2, GroupID);
            pst.setString(3, SubGroupID);
            pst.setString(4, SessionID);
            pst.setString(5, Time);
           int k = pst.executeUpdate();
           
           if(k==1){
               JOptionPane.showMessageDialog(this," Added");
             
                
                cmb_lec.setSelectedItem("");
                cmb_gid.setSelectedItem("");
                cmb_sid.setSelectedItem("");
                cmb_session.setSelectedItem("");
                cmb_time.setSelectedItem("");
              
             
             ck.AddRowToJTable(new Object[]{
                
                cmb_lec.getSelectedItem().toString(),cmb_gid.getSelectedItem().toString(),cmb_gid.getSelectedItem().toString(),cmb_sid.getSelectedItem().toString(),
                    cmb_session.getSelectedItem().toString(),cmb_time.getSelectedItem().toString(),
                
                }); 
               
               
           }
           else{
               JOptionPane.showMessageDialog(this,"Error");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               
                cmb_lec.setSelectedIndex(0);
                cmb_gid.setSelectedIndex(0);
                cmb_sid.setSelectedIndex(0);
                cmb_session.setSelectedIndex(0);
                cmb_time.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Btn_GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GraphActionPerformed
        // TODO add your handling code here:
        statistics1 s =new statistics1();
        s.show();
        dispose();
    }//GEN-LAST:event_Btn_GraphActionPerformed

    private void Btn_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LocationActionPerformed
        // TODO add your handling code here:
        Addkocation adl = new Addkocation();
        adl.show();
        dispose();
    }//GEN-LAST:event_Btn_LocationActionPerformed

    private void Btn_TagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TagActionPerformed
        // TODO add your handling code here:
        addtag  as =new addtag();
        as.show();
        dispose();
    }//GEN-LAST:event_Btn_TagActionPerformed

    private void Btn_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DayActionPerformed
        // TODO add your handling code here:
        addWorking ad = new addWorking();
        ad.show();;
        dispose();
    }//GEN-LAST:event_Btn_DayActionPerformed

    private void Btn_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StudentActionPerformed
        // TODO add your handling code here:
        add_student  as =new add_student();
        as.show();
        dispose();
    }//GEN-LAST:event_Btn_StudentActionPerformed

    private void Btn_SubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubjectActionPerformed
        // TODO add your handling code here:
        Addsubject adl = new  Addsubject();
        adl.show();
        dispose();
    }//GEN-LAST:event_Btn_SubjectActionPerformed

    private void Btn_SessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SessionActionPerformed
        // TODO add your handling code here:
         AddSession  as =new AddSession();
        as.show();
        dispose();
    }//GEN-LAST:event_Btn_SessionActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        mainMenu mm = new mainMenu();
          mm.show();
          dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_le.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_le.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_le.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_le.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Session_NotAvai_le().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABC;
    private javax.swing.JButton Btn_Day;
    private javax.swing.JButton Btn_Graph;
    private javax.swing.JButton Btn_Lecture;
    private javax.swing.JButton Btn_Location;
    private javax.swing.JButton Btn_Session;
    private javax.swing.JButton Btn_Student;
    private javax.swing.JButton Btn_Subject;
    private javax.swing.JButton Btn_Tag;
    private javax.swing.JButton btn_addLec;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_mnLec;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_gid;
    private javax.swing.JComboBox<String> cmb_lec;
    private javax.swing.JComboBox<String> cmb_session;
    private javax.swing.JComboBox<String> cmb_sid;
    private javax.swing.JComboBox<String> cmb_time;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    

    
}
