/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.itpm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WindowsUser
 */
public class Session_NotAvai_ml extends javax.swing.JFrame {

    /**
     * Creates new form Session_NotAvailableTime
     */
    public Session_NotAvai_ml() {
        initComponents();
        Connect();
        ComboRoom();
        notAviLoc_load();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    void  notAviLoc_load(){
        int c;
        try {
            pst=con.prepareStatement("select* from notavailablelocation");
            rs=pst.executeQuery();
            
            ResultSetMetaData rsd=rs.getMetaData();
            c=rsd.getColumnCount();
            
            DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next()){
                Vector v2= new Vector();
                for(int i=1;i<=c;i++){
                   
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("roomName"));
                    v2.add(rs.getString("day"));
                    v2.add(rs.getString("startTime"));
                    v2.add(rs.getString("endTime"));
                    
                    
                }
                d.addRow(v2);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    void ComboRoom(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable_manage","root","");
            pst = con.prepareStatement("Select distinct roomname from locationdetails");
            ResultSet rs= pst.executeQuery();
            
            while(rs.next()){
              cmb_room.addItem(rs.getString("roomname"));
              cmb_room.setSelectedItem("");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public  void AddRowToJTable(Object[] dataRow){
         
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(dataRow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ABC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Lecture = new javax.swing.JButton();
        Btn_Student = new javax.swing.JButton();
        Btn_Subject = new javax.swing.JButton();
        Btn_Location = new javax.swing.JButton();
        Btn_Tag = new javax.swing.JButton();
        Btn_Session = new javax.swing.JButton();
        Btn_Day = new javax.swing.JButton();
        Btn_Graph = new javax.swing.JButton();
        btn_con = new javax.swing.JButton();
        btn_nonOver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_stu = new javax.swing.JButton();
        btn_lec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmb_room = new javax.swing.JComboBox<>();
        cmb_day = new javax.swing.JComboBox<>();
        cmb_Stime = new javax.swing.JComboBox<>();
        cmb_Etime = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_dl = new javax.swing.JButton();
        btn_cnl = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        ABC.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ABC.setText("ABC");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Insitution");

        Btn_Lecture.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Lecture.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Lecture.setText("Lecturer");
        Btn_Lecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LectureActionPerformed(evt);
            }
        });

        Btn_Student.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Student.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Student.setText("Student");
        Btn_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StudentActionPerformed(evt);
            }
        });

        Btn_Subject.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Subject.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Subject.setText("Subject");
        Btn_Subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SubjectActionPerformed(evt);
            }
        });

        Btn_Location.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Location.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Location.setText("Location");
        Btn_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LocationActionPerformed(evt);
            }
        });

        Btn_Tag.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Tag.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Tag.setText("Tag");
        Btn_Tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TagActionPerformed(evt);
            }
        });

        Btn_Session.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Session.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Session.setText("Session");
        Btn_Session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SessionActionPerformed(evt);
            }
        });

        Btn_Day.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Day.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Day.setText("Day & Time");
        Btn_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DayActionPerformed(evt);
            }
        });

        Btn_Graph.setBackground(new java.awt.Color(255, 255, 51));
        Btn_Graph.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Btn_Graph.setText("Graph");
        Btn_Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GraphActionPerformed(evt);
            }
        });

        btn_con.setBackground(new java.awt.Color(153, 153, 255));
        btn_con.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_con.setText("Consecutive");
        btn_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conActionPerformed(evt);
            }
        });

        btn_nonOver.setBackground(new java.awt.Color(153, 153, 255));
        btn_nonOver.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_nonOver.setText("Non Overlapping");
        btn_nonOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nonOverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Not available time");

        btn_stu.setBackground(new java.awt.Color(255, 255, 102));
        btn_stu.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_stu.setText("Student");
        btn_stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stuActionPerformed(evt);
            }
        });

        btn_lec.setBackground(new java.awt.Color(255, 255, 153));
        btn_lec.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btn_lec.setText("Lecturer");
        btn_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lecActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Location");

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room ID", "Day", "Start Time", "End Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Select Room");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Select Day");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Start Time");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("End Time");

        cmb_room.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_roomActionPerformed(evt);
            }
        });

        cmb_day.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        cmb_day.setSelectedIndex(-1);
        cmb_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_dayActionPerformed(evt);
            }
        });

        cmb_Stime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_Stime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8.30", "9.30", "10.30", "11.30", "12.30", "1.30", "2.30", "3.30", "4.30" }));
        cmb_Stime.setSelectedIndex(-1);
        cmb_Stime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_StimeActionPerformed(evt);
            }
        });

        cmb_Etime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_Etime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9.30", "10.30", "11.30", "12.30", "1.30", "2.30", "3.30", "4.30", "5.30" }));
        cmb_Etime.setSelectedIndex(-1);
        cmb_Etime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_EtimeActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(255, 255, 102));
        btn_add.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(255, 255, 102));
        btn_update.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_dl.setBackground(new java.awt.Color(255, 102, 51));
        btn_dl.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_dl.setText("Delete");
        btn_dl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dlActionPerformed(evt);
            }
        });

        btn_cnl.setBackground(new java.awt.Color(102, 51, 255));
        btn_cnl.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_cnl.setText("cancel");
        btn_cnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cnlActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(255, 102, 255));
        btn_back.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btn_back.setText("Back to main manu ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_stu, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_nonOver)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btn_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(143, 143, 143))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Tag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Day, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(Btn_Lecture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Btn_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btn_con, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(405, 405, 405))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cmb_Etime, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cmb_Stime, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(47, 47, 47)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cmb_day, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cmb_room, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                    .addComponent(btn_dl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btn_cnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ABC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addGap(78, 78, 78)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ABC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btn_con)
                            .addComponent(btn_nonOver)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_stu)
                            .addComponent(btn_lec)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(Btn_Lecture)
                        .addGap(32, 32, 32)
                        .addComponent(Btn_Subject)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Student)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Location)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Btn_Tag)
                                .addComponent(jLabel5)
                                .addComponent(cmb_room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btn_update)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn_Session)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_Day)
                                    .addComponent(btn_dl))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cmb_Stime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Graph)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cmb_Etime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cnl))))
                        .addGap(43, 43, 43)
                        .addComponent(btn_add)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back)
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_LectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LectureActionPerformed
        // TODO add your handling code here:
         Addlecturer al =new Addlecturer();
        al.show();
        dispose();
    }//GEN-LAST:event_Btn_LectureActionPerformed

    private void btn_nonOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nonOverActionPerformed
        // TODO add your handling code here:
        NonOversession1 no= new NonOversession1();
        no.show();
        dispose();
    }//GEN-LAST:event_btn_nonOverActionPerformed

    private void cmb_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_roomActionPerformed

    private void cmb_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_dayActionPerformed

    private void cmb_StimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_StimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_StimeActionPerformed

    private void cmb_EtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_EtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_EtimeActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
         DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
         int selectIndex= jTable1.getSelectedRow();
         
         int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
         
           
        String RoomName= cmb_room.getSelectedItem().toString();
        String Day= cmb_day.getSelectedItem().toString();
        String StartTime= cmb_Stime.getSelectedItem().toString();
        String EndTime= cmb_Etime.getSelectedItem().toString();
        
        
        try {
            pst=con.prepareStatement("update notavailablelocation set roomName=?,day=?,startTime=?,endTime=? where id=? ");
            
            pst.setString(1, RoomName);
            pst.setString(2, Day);
            pst.setString(3, StartTime);
            pst.setString(4, EndTime);
           
            pst.setInt(5,id);
            
           int k = pst.executeUpdate();
           
           if(k==1){
               JOptionPane.showMessageDialog(this,"Updated");
             
                cmb_room.setSelectedItem("");
                cmb_day.setSelectedItem("");
                cmb_Stime.setSelectedItem("");
                cmb_Etime.setSelectedItem("");
                
                
                notAviLoc_load();
               
               
           }
           else{
               JOptionPane.showMessageDialog(this,"Error");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_dlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dlActionPerformed
        // TODO add your handling code here:

        DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
        int selectIndex= jTable1.getSelectedRow();

        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        try {
            pst=con.prepareStatement("delete from notavailablelocation  where id=?");

            pst.setInt(1, id);

            int k = pst.executeUpdate();

            if(k==1){
                JOptionPane.showMessageDialog(this,"Not available location Updated");

                
                cmb_room.setSelectedItem("");
                cmb_day.setSelectedItem("");
                cmb_Stime.setSelectedItem("");
                cmb_Etime.setSelectedItem("");
                btn_add.setEnabled(true);
                notAviLoc_load();

            }
            else{
                JOptionPane.showMessageDialog(this,"Error");
            }

        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_dlActionPerformed

    private void btn_cnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cnlActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_btn_cnlActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel d1=(DefaultTableModel)jTable1.getModel();
         int selectIndex= jTable1.getSelectedRow();
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
         
      
         cmb_room.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());
         cmb_day.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
         cmb_Stime.setSelectedItem(d1.getValueAt(selectIndex,3).toString());
         cmb_Etime.setSelectedItem(d1.getValueAt(selectIndex, 4).toString());
         
        btn_add.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String RoomName= cmb_room.getSelectedItem().toString();
        String Day= cmb_day.getSelectedItem().toString();
        String StartTime= cmb_Stime.getSelectedItem().toString();
        String EndTime= cmb_Etime.getSelectedItem().toString();
        try {
            pst=con.prepareStatement("insert into notavailablelocation(roomName,day,startTime,endTime)values(?,?,?,?)");
           
            pst.setString(1, RoomName);
            pst.setString(2, Day);
            pst.setString(3, StartTime);
            pst.setString(4, EndTime);
            
           int k = pst.executeUpdate();
           
           if(k==1){
               JOptionPane.showMessageDialog(this," Added");
             
                cmb_room.setSelectedItem("");
                cmb_day.setSelectedItem("");
                cmb_Stime.setSelectedItem("");
                cmb_Etime.setSelectedItem("");
                
                cmb_room.requestFocus();
                notAviLoc_load();
               
               
           }
           else{
               JOptionPane.showMessageDialog(this,"Error");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(ck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void Btn_SubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SubjectActionPerformed
        // TODO add your handling code here:
         Addsubject adl = new  Addsubject();
        adl.show();
        dispose();
    }//GEN-LAST:event_Btn_SubjectActionPerformed

    private void Btn_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StudentActionPerformed
        // TODO add your handling code here:
        add_student  as =new add_student();
        as.show();
        dispose();
    }//GEN-LAST:event_Btn_StudentActionPerformed

    private void Btn_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LocationActionPerformed
        // TODO add your handling code here:
        Addkocation adl = new Addkocation();
        adl.show();
        dispose();
    }//GEN-LAST:event_Btn_LocationActionPerformed

    private void Btn_TagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TagActionPerformed
        // TODO add your handling code here:
        addtag  as =new addtag();
        as.show();
        dispose();
    }//GEN-LAST:event_Btn_TagActionPerformed

    private void Btn_SessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SessionActionPerformed
        // TODO add your handling code here:
        AddSession  as =new AddSession();
        as.show();
        dispose();
    }//GEN-LAST:event_Btn_SessionActionPerformed

    private void Btn_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DayActionPerformed
        // TODO add your handling code here:
        addWorking ad = new addWorking();
        ad.show();;
        dispose();
        
    }//GEN-LAST:event_Btn_DayActionPerformed

    private void Btn_GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GraphActionPerformed
        // TODO add your handling code here:
         statistics1 s =new statistics1();
        s.show();
        dispose();
    }//GEN-LAST:event_Btn_GraphActionPerformed

    private void btn_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conActionPerformed
        // TODO add your handling code here:
        Consession c= new Consession();
        c.show();
        dispose();
    }//GEN-LAST:event_btn_conActionPerformed

    private void btn_stuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stuActionPerformed
        // TODO add your handling code here:
        Session_NotAvai_sm ns=new Session_NotAvai_sm();
        ns.show();
        dispose();
        
    }//GEN-LAST:event_btn_stuActionPerformed

    private void btn_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lecActionPerformed
        // TODO add your handling code here:
        Session_NotAvai_lem nlec=new Session_NotAvai_lem();
        nlec.show();
        dispose();
    }//GEN-LAST:event_btn_lecActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        mainMenu mm = new mainMenu();
          mm.show();
          dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_ml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_ml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_ml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Session_NotAvai_ml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Session_NotAvai_ml().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABC;
    private javax.swing.JButton Btn_Day;
    private javax.swing.JButton Btn_Graph;
    private javax.swing.JButton Btn_Lecture;
    private javax.swing.JButton Btn_Location;
    private javax.swing.JButton Btn_Session;
    private javax.swing.JButton Btn_Student;
    private javax.swing.JButton Btn_Subject;
    private javax.swing.JButton Btn_Tag;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cnl;
    private javax.swing.JButton btn_con;
    private javax.swing.JButton btn_dl;
    private javax.swing.JButton btn_lec;
    private javax.swing.JButton btn_nonOver;
    private javax.swing.JButton btn_stu;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_Etime;
    private javax.swing.JComboBox<String> cmb_Stime;
    private javax.swing.JComboBox<String> cmb_day;
    private javax.swing.JComboBox<String> cmb_room;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
